version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=ai6.ir
      - NGINX_PORT=80
    volumes:
      - ./front/dist:/usr/share/nginx/html
  #      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
  #      - /home/ubuntu/ssl:/ssl/
