version: "3.9"
services:
  api:
    image: node:17.8.0
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
    environment:
      DB_ADDRESS : "mongo:27017"
      DB_USERNAME : "username"
      DB_PASSWORD : "password"
      SECRET: supersecret
      TZ : "Asia/Tehran"
    working_dir: /app
    networks:
      - network
    command: bash -c "npm install && npm start"

networks:
  network:
    driver: bridge
