version: "3.9"
services:
  api:
    image: node:17.8.0
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      DB_ADDRESS : "156.253.5.25:27017"
      DB_USERNAME : "username"
      DB_PASSWORD : "password"
      SECRET: supersecret
      TZ : "Asia/Tehran"
    working_dir: /app
    command: bash -c "npm install && npm start"

