version: "3.9"
services:
  api:
    image: node
    restart: always
    depends_on:
      - "mongo"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      SECRET: supersecret
      TZ : "Asia/Tehran"
    working_dir: /app
    command: bash -c "npm install && npm start"
    networks:
      - network

  mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - network

  front:
    image: node
    restart: always
    depends_on:
      - "api"
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      API_URL : "http://api:3000/api/v1"

networks:
  network:
    driver: bridge

