version: "3.9"
services:
  mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE : "handover"
      MONGO_INITDB_ROOT_USERNAME : "username"
      MONGO_INITDB_ROOT_PASSWORD : "password"
    networks:
      - network

  api:
    image: node:17.8.0
    restart: always
    depends_on:
      - "mongo"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      DB_ADDRESS : "mongo:27017"
      DB_USERNAME: "username"
      DB_PASSWORD: "password"
      SECRET: supersecret
      TZ : "Asia/Tehran"
    working_dir: /app
    command: bash -c "npm install && npm start"
    networks:
      - network

#  mongo:
#    image: mongo:4.4.6
#    restart: always
#    volumes:
#      - ./data/db:/data/db
#    ports:
#      - "27017:27017"
#    networks:
#      - network

  vue:
    image: node:17.8.0
    restart: always
    depends_on:
      - "api"
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider

networks:
  network:
    driver: bridge

