version: "3.9"
services:
  api:
    image: node:17.8.0
    restart: always
    depends_on:
      - "mongo"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      DB_ADDRESS : "mongo:27017"
      DB_USERNAME : "username"
      DB_PASSWORD : "password"
      SECRET: supersecret
      TZ : "Asia/Tehran"
    working_dir: /app
    command: bash -c "npm install && npm start"
    networks:
      - network

  mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_DATABASE : "handover"
#      MONGO_INITDB_ROOT_USERNAME : "username"
#      MONGO_INITDB_ROOT_PASSWORD : "password"
    networks:
      - network

#  front:
#    image: node:17.8.0
#    restart: always
#    ports:
#      - "8000:80"
#    volumes:
#      - ./front:/app
#    working_dir: /app
#    command: bash -c "npm run build"
#    environment:
#      NODE_OPTIONS: --openssl-legacy-provider
#    networks:
#      - network

  nginx:
    image: nginx:1.23
    restart: unless-stopped
    ports:
      - 8080:80
      - 4433:443
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./front/dist:/usr/share/nginx/html
#      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
#      - /home/ubuntu/ssl:/ssl/

networks:
  network:
    driver: bridge

