version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front/dist:/usr/share/nginx/html/ai6
      - ./nginx/certs:/etc/nginx/certs
  #      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
  #      - /home/ubuntu/ssl:/ssl/
