version: "3.9"
services:
  vue:
    image: node:17.8.0
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider

networks:
  network:
    driver: bridge
