version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./front/dist:/usr/share/nginx/html/ai6
      - ./data/certs:/etc/nginx/certs
  #      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
  #      - /home/ubuntu/ssl:/ssl/
